/**
 * **@noy-db/as-sql** — SQL dump export for migration.
 *
 * One-way, at-export-time string formatter that emits dialect-aware
 * `CREATE TABLE` + `INSERT INTO` statements. This is NOT a runtime
 * SQL query frontend — it's the migration bridge for consumers moving
 * noy-db data into Postgres, MySQL, or SQLite.
 *
 * Column types are inferred from value types in the first 100 records
 * per collection. Every record's row uses parameterless inline-literal
 * INSERT (no prepared statements) so the dump loads with a single
 * `psql -f`, `mysql <`, or `sqlite3 < dump.sql` invocation.
 *
 * **Zero dependencies** — hand-rolled string formatter, ~300 LoC.
 *
 * See `docs/patterns/as-exports.md` for the three-tier egress model.
 *
 * @packageDocumentation
 */

import type { Vault } from '@noy-db/hub'
import type { ExportChunk, NoydbFormat, FormatExportOptions } from '@noy-db/hub/as'

export type SqlDialect = 'postgres' | 'mysql' | 'sqlite'
export type SqlMode = 'schema-only' | 'data-only' | 'schema+data'

export interface AsSQLOptions {
  /** Target dialect. Default `'postgres'`. */
  readonly dialect?: SqlDialect
  /** Collection allowlist. Omit for all. */
  readonly include?: readonly string[]
  /** Schema + data, schema only, or data only. Default `'schema+data'`. */
  readonly mode?: SqlMode
  /** Map collection name → table name. Default identity. */
  readonly tableNames?: (collection: string) => string
  /** Include `_noydb_version` / `_noydb_ts` metadata columns. Default `false`. */
  readonly metadataColumns?: boolean

  /**
   * Apply the hub's `applyListProjection` read-projection before
   * serialising rows. `true` redacts only `classifiedFields` (mask /
   * omit / rider, per the field's preset). The object form additionally
   * redacts fields carrying a plain `fieldMeta` `sensitivity: 'pii' |
   * 'secret'` tag, per `sensitivity: 'omit' | 'mask'`.
   *
   * Caveat: `describe()` reflects the declarations of *this session's*
   * collection instance — redaction only takes effect when the
   * collection was opened (this call or earlier in the session) with
   * its `classifiedFields` / `fieldMeta` options. This is presentation-
   * layer redaction; it never affects what's on disk. Sealed handles
   * are unaffected either way — they always serialize as `'[sealed]'`,
   * so ciphertext never leaks regardless of this option.
   *
   * Rider companion fields (e.g. `pan_last4`) remain visible as their
   * own columns — they are safe write-time projections.
   */
  readonly redact?: boolean | { readonly sensitivity: 'omit' | 'mask' }
}

export interface AsSQLDownloadOptions extends AsSQLOptions {
  /** Filename offered to the browser. Default `'vault-export.sql'`. */
  readonly filename?: string
}

export interface AsSQLWriteOptions extends AsSQLOptions {
  /** Required for Node file-write — Tier 3 risk gate. */
  readonly acknowledgeRisks: true
}

/**
 * The pure encoder — records in, SQL out. Already gated and already redacted
 * by hub; it has no vault (ADR 0004).
 */
function encodeSql(chunks: readonly ExportChunk[], options: AsSQLFormatOptions = {}): string {
  const dialect = options.dialect ?? 'postgres'
  const mode = options.mode ?? 'schema+data'
  const tableName = options.tableNames ?? ((c: string) => c)
  const includeAll = !options.include || options.include.length === 0
  const allowlist = options.include ? new Set(options.include) : null

  // Bucket records by collection so we can emit schema+data atomically.
  const buckets = new Map<string, Record<string, unknown>[]>()
  for (const chunk of chunks) {
    if (!includeAll && allowlist && !allowlist.has(chunk.collection)) continue
    const records = chunk.records.map((r: unknown) => stripMeta(r as Record<string, unknown>))


    const bucket = buckets.get(chunk.collection) ?? []
    bucket.push(...records)
    buckets.set(chunk.collection, bucket)
  }

  const parts: string[] = []
  parts.push(`-- Generated by @noy-db/as-sql · dialect: ${dialect} · mode: ${mode}`)
  parts.push(`-- Bundle snapshot — NOT a live connection. Load with: ${loadCommand(dialect)}`)
  parts.push('')

  for (const [collection, records] of buckets) {
    const table = tableName(collection)
    const schema = inferSchema(records, options.metadataColumns === true)
    if (mode !== 'data-only') {
      parts.push(createTable(dialect, table, schema))
      parts.push('')
    }
    if (mode !== 'schema-only') {
      for (const rec of records) {
        parts.push(insertRow(dialect, table, schema, rec))
      }
      parts.push('')
    }
  }

  return parts.join('\n')
}

/** Options a SQL format instance carries. Read concerns live on `vault.export`. */
export interface AsSQLFormatOptions {
  /** Target dialect. Default `'postgres'`. */
  readonly dialect?: SqlDialect
  /** Schema + data, schema only, or data only. Default `'schema+data'`. */
  readonly mode?: SqlMode
  /** Map collection name → table name. Default identity. */
  readonly tableNames?: (collection: string) => string
  /** Include `_noydb_version` / `_noydb_ts` metadata columns. Default `false`. */
  readonly metadataColumns?: boolean
  /**
   * Collection allowlist, kept here as well as on `vault.export` because the
   * encoder buckets by collection. `readOpts` forwards it to the READ so hub
   * does not decrypt what will not be emitted.
   */
  readonly include?: readonly string[]
}

/**
 * The SQL format — the `as-*` port instance.
 *
 * Export-only: SQL has no round-trip here, so `decode` is absent and
 * `vault.import(asSql(), …)` throws naming the format. That is a property of
 * this implementation, not of the contract.
 */
export function asSql(options: AsSQLFormatOptions = {}): NoydbFormat<string> {
  return {
    id: 'sql',
    extension: 'sql',
    mimeType: 'application/sql;charset=utf-8',
    tier: 'plaintext',
    encode: (chunks) => encodeSql(chunks, options),
  }
}

/** Only the keys actually set — `exactOptionalPropertyTypes` is on. */
function readOpts(o: AsSQLOptions): FormatExportOptions {
  return {
    ...(o.include ? { collections: o.include } : {}),
    ...(o.redact !== undefined && o.redact !== false
      ? { redact: o.redact === true ? true : { sensitivity: o.redact.sensitivity } }
      : {}),
  }
}

/** Browser download. Hub gates, reads and redacts; this wraps the bytes. */
export async function download(vault: Vault, options: AsSQLDownloadOptions = {}): Promise<void> {
  const fmt = asSql(options)
  const sql = await vault.export(fmt, readOpts(options))
  const url = URL.createObjectURL(new Blob([sql], { type: fmt.mimeType }))
  const a = document.createElement('a')
  a.href = url
  a.download = options.filename ?? `vault-export.${fmt.extension}`
  a.click()
  URL.revokeObjectURL(url)
}

/**
 * Node file write. Not in hub because `hub-portable` forbids Node builtins
 * there — hub must run in a browser, Worker, Deno and Bun. The gate, the read
 * and the redaction all moved; these lines are the runtime-specific part.
 */
export async function write(vault: Vault, path: string, options: AsSQLWriteOptions): Promise<void> {
  if (options.acknowledgeRisks !== true) {
    throw new Error(
      'as-sql.write: acknowledgeRisks: true is required for on-disk plaintext output.',
    )
  }
  const sql = await vault.export(asSql(options), readOpts(options))
  const { writeFile } = await import('node:fs/promises')
  await writeFile(path, sql, 'utf8')
}


// ─── SQL formatting internals ───────────────────────────────────────────

type SqlType = 'text' | 'integer' | 'real' | 'boolean' | 'timestamp' | 'jsonb'

interface ColumnSchema {
  readonly name: string
  readonly type: SqlType
  readonly nullable: boolean
}

function inferSchema(records: readonly Record<string, unknown>[], includeMeta: boolean): ColumnSchema[] {
  const observed = new Map<string, { types: Set<SqlType>; nullable: boolean }>()
  const sample = records.slice(0, 100) // sample up to 100 rows for type inference
  for (const rec of sample) {
    for (const key of Object.keys(rec)) {
      if (!observed.has(key)) observed.set(key, { types: new Set(), nullable: false })
      const slot = observed.get(key)!
      const value = rec[key]
      if (value === null || value === undefined) {
        slot.nullable = true
        continue
      }
      slot.types.add(inferType(value))
    }
    // Fields missing from this record → nullable
    for (const key of observed.keys()) {
      if (!(key in rec)) observed.get(key)!.nullable = true
    }
  }

  const columns: ColumnSchema[] = []
  for (const [name, info] of observed) {
    if (!includeMeta && (name === '_v' || name === '_ts' || name === '_by')) continue
    const type: SqlType = info.types.size === 1
      ? [...info.types][0]!
      : 'text' // mixed types → fall back to text
    columns.push({ name, type, nullable: info.nullable })
  }
  if (includeMeta) {
    columns.push({ name: '_noydb_version', type: 'integer', nullable: true })
    columns.push({ name: '_noydb_ts', type: 'timestamp', nullable: true })
  }
  return columns
}

function inferType(value: unknown): SqlType {
  if (typeof value === 'boolean') return 'boolean'
  if (typeof value === 'number') return Number.isInteger(value) ? 'integer' : 'real'
  if (value instanceof Date) return 'timestamp'
  if (typeof value === 'string') {
    if (/^\d{4}-\d{2}-\d{2}T/.test(value)) return 'timestamp'
    return 'text'
  }
  return 'jsonb'
}

function createTable(dialect: SqlDialect, table: string, schema: readonly ColumnSchema[]): string {
  const cols = schema.map(c => `  ${quoteIdent(dialect, c.name)} ${mapType(dialect, c.type)}${c.nullable ? '' : ' NOT NULL'}`)
  return `CREATE TABLE ${quoteIdent(dialect, table)} (\n${cols.join(',\n')}\n);`
}

function mapType(dialect: SqlDialect, type: SqlType): string {
  const map: Record<SqlDialect, Record<SqlType, string>> = {
    postgres: { text: 'TEXT', integer: 'INTEGER', real: 'REAL', boolean: 'BOOLEAN', timestamp: 'TIMESTAMPTZ', jsonb: 'JSONB' },
    mysql:    { text: 'TEXT', integer: 'BIGINT', real: 'DOUBLE', boolean: 'TINYINT(1)', timestamp: 'DATETIME', jsonb: 'JSON' },
    sqlite:   { text: 'TEXT', integer: 'INTEGER', real: 'REAL', boolean: 'INTEGER', timestamp: 'TEXT', jsonb: 'TEXT' },
  }
  return map[dialect][type]
}

function insertRow(
  dialect: SqlDialect,
  table: string,
  schema: readonly ColumnSchema[],
  record: Record<string, unknown>,
): string {
  const cols = schema.map(c => quoteIdent(dialect, c.name)).join(', ')
  const values = schema.map(c => formatLiteral(dialect, c.type, record[c.name])).join(', ')
  return `INSERT INTO ${quoteIdent(dialect, table)} (${cols}) VALUES (${values});`
}

function formatLiteral(dialect: SqlDialect, type: SqlType, value: unknown): string {
  if (value === null || value === undefined) return 'NULL'
  if (type === 'boolean') {
    if (dialect === 'mysql' || dialect === 'sqlite') return value ? '1' : '0'
    return value ? 'TRUE' : 'FALSE'
  }
  if (type === 'integer' || type === 'real') return stringifyScalar(value)
  if (type === 'timestamp') {
    const s = value instanceof Date ? value.toISOString() : stringifyScalar(value)
    return quoteString(dialect, s)
  }
  if (type === 'jsonb') {
    return quoteString(dialect, JSON.stringify(value))
  }
  return quoteString(dialect, stringifyScalar(value))
}

function stringifyScalar(value: unknown): string {
  if (typeof value === 'string') return value
  if (typeof value === 'number' || typeof value === 'boolean' || typeof value === 'bigint') {
    return String(value)
  }
  if (value === null || value === undefined) return ''
  return JSON.stringify(value)
}

function quoteString(dialect: SqlDialect, s: string): string {
  // Both standard SQL and common dialects use '' to escape single quotes.
  const escaped = s.replace(/'/g, "''")
  return `'${escaped}'`
}

function quoteIdent(dialect: SqlDialect, name: string): string {
  if (dialect === 'mysql') return `\`${name.replace(/`/g, '``')}\``
  return `"${name.replace(/"/g, '""')}"`
}

function loadCommand(dialect: SqlDialect): string {
  if (dialect === 'postgres') return 'psql -f dump.sql'
  if (dialect === 'mysql') return 'mysql -u <user> -p < dump.sql'
  return 'sqlite3 <database>.db < dump.sql'
}

function stripMeta(record: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {}
  for (const [key, value] of Object.entries(record)) {
    if (key === '_iv' || key === '_data' || key === '_noydb') continue
    out[key] = value
  }
  return out
}
